### ISSUE TITLE
DISCUSSION: tag line on docs is confusing to many.

### ISSUE THREAD

**Issue by tobowers** [Amicus/end-dash#165]
"EndDash is a bindings-aware client-side templating framework built on top of valid HTML."

Many don't immediately know what "bindings-aware" means.  Advanced users will still take a sec to figure it out.

My suggestion:

EndDash is a javascript templating framework built on top of valid HTML that allows bidirectional binding of Backbone objects to the DOM.

**Comment by tobowers** [comment]
moving discussion to https://github.com/Amicus/end-dash/issues/165

**Comment by yaymukund** [comment]
I don't get it. This is #165.

**Comment by tobowers** [comment]
I mean: https://github.com/Amicus/end-dash/pull/157
