### ISSUE TITLE
Removing awesome-docs documentation

### ISSUE THREAD

**Issue by yaymukund** [Amicus/end-dash#25]
@bglusman 

cc suspenders.js compadre @devmanhinton 

This came up in #24 :

> Also, the two .markdown tests look to be the old AwesomeDocs tests, I think Topper replaced/converted all of those to mocha, are they still needed?

I started looking at this. The tests are _within_ the documentation, so it's tricky to decouple them in such a way that the documentation still makes any sense.

We have "clean up documentation" as part of this sprint, so we'll address it in more detail later this week. I'll leave this issue open as a reminder— does that sound reasonable, @bglusman ?

**Comment by bglusman** [comment]
Yeah, sounds reasonable, can totally leave them as docs and just stop
running/evaluating awesome-docs tests I think, but not a big deal either
way.

Brian Glusman - brian@amicushq.com
215-460-9585 - _cell_
_Twitter_: @amicushq

**Comment by yaymukund** [comment]
Think this is closed since we did a bunch of refactoring to the docs.
