### ISSUE TITLE
rivets.js

### ISSUE THREAD

**Issue by tobowers** [Amicus/end-dash#85]
hmmm - this is my first time seeing this:

http://rivetsjs.com/  has some interesting plugin and syntax choices.

**Comment by tobowers** [comment]
@xcoderzach @yaymukund @devmanhinton @bglusman ping if you don't get these.

**Comment by xcoderzach** [comment]
Wow that's totally different than it was when I saw it a few months ago

**Comment by devmanhinton** [comment]
Wow, yeah, That is definitely good to be aware of !
