### ISSUE TITLE
better syntax for variables

### ISSUE THREAD

**Issue by xcoderzach** [Amicus/end-dash#9]
variables need a better syntax.

``` html
<div class="user-">
  user's name is #{name}.
</div>
```

would be sick.

**Comment by xcoderzach** [comment]
NOTE TO SELF:
https://developer.mozilla.org/en-US/docs/Web/API/Text.splitText makes this super simple!  HAH HA!

**Comment by yaymukund** [comment]
I think this is a duplicate of #73 ?
